### PR TITLE
Add ability to skip reload scripts/commands

### PR DESCRIPTION
**Pull request by thklein**

### CODE REVIEW

**Comment by thklein** [comment]
Ping @clue 
Based on executor concept to achieve cleaner solution

**Comment by clue** [comment]
Thank you for the high quality PR! This is currently a bit difficult to review, can you rebase this now that #29 is in? :+1:

**Comment by thklein** [comment]
Rebase done!

**Comment by clue** [comment]
Thank you for the high quality PR and the quick update, change LGTM! :shipit: :+1:

**Pull request merged**
