### PR TITLE
Use GitHub actions for continuous integration (CI)

### PR DESCRIPTION
**Pull request by SimonFrings**
Bye bye Travis CI, you've served us well.

Builds on top of reactphp/reactphp#442.

### CODE REVIEW

**Comment by SimonFrings** [comment]
@clue don't forget to activate GitHub actions.

**Review by clue — APPROVED** [review]
@SimonFrings Thanks for the update, changes LGTM! :shipit:

**Comment by clue** [comment]
After approving, I just noticed the legacy HHVM build currently fails. Is this something you can look into?

**Comment by SimonFrings** [comment]
I took a look and it seems like HHVM can't even execute confgen properly. I don't see a fast solution to this other then to drop HHVM support in a following pull request. Part of this reason is HHVM's decrease in use (if no one uses it why going through the trouble).

**Comment by clue** [comment]
Fair point, let's get this in as-is and drop HHVM support entirely in a follow-up PR :shipit:

**Pull request merged**
